### ISSUE TITLE
RuntimeError: Function AddBackward0 returned an invalid gradient at index 1 - expected type torch.cuda.FloatTensor but got torch.FloatTensor

### ISSUE THREAD

**Issue by ComplicatedPhenomenon** [HelenGuohx/logbert#3]
Hi, @HelenGuohx  Could you please have a look at this problem?
```
○ → sh run_logbert_bgl_2k.sh
tee: bgl/logbert/bgl_2k_0.5_6.log: 没有那个文件或目录
Parsing file: /home/wm/.dataset/bgl/BGL_2k.log
Total size after encoding is 2000 2000
Parsing done. [Time taken: 0:00:00.151386]
Loading ../output/bgl/BGL_2k.log_structured.csv
there are 1880 instances (sliding windows) in this dataset

training size 684
test normal size 1028
test abnormal size 168
Save options parameters
Loading vocab ../output/bgl/vocab.pkl
vocab Size:  73

Loading Train Dataset
before filtering short session
train size  616
valid size  68
========================================
========================================
Num of train seqs 616
Num of valid seqs 68
========================================

Loading valid Dataset
Creating Dataloader
Building BERT model
Creating BERT Trainer
Total Parameters: 2147402
Training Start


start calculate center

100%|██████████| 19/19 [00:00<00:00, 126.17it/s]
100%|██████████| 2/2 [00:00<00:00, 31.87it/s]
Traceback (most recent call last):
  File "../main_run.py", line 175, in <module>
    main()
  File "../main_run.py", line 163, in main
    run_logbert(options)
  File "/home/wm/logbert/logbert/bert.py", line 15, in run_logbert
    Trainer(options).train()
  File "/home/wm/logbert/logbert/bert_pytorch/train_log.py", line 115, in train
    self.start_iteration(surfix_log="log")
  File "/home/wm/logbert/logbert/bert_pytorch/train_log.py", line 128, in start_iteration
    _, train_dist = self.trainer.train(epoch)
  File "/home/wm/logbert/logbert/bert_pytorch/trainer/pretrain.py", line 101, in train
    return self.iteration(epoch, self.train_data)
  File "/home/wm/logbert/logbert/bert_pytorch/trainer/pretrain.py", line 172, in iteration
    loss.backward()
  File "/home/wm/miniconda3/lib/python3.8/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/wm/miniconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 97, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Function AddBackward0 returned an invalid gradient at index 1 - expected type torch.cuda.FloatTensor but got torch.FloatTensor
```

**Comment by ComplicatedPhenomenon** [comment]
Problem solved.  `time_loss` isn't  always on GPU as 
         ```
           time_loss = torch.tensor(0) if not self.is_time else self.time_criterion(
                mask_time_output.squeeze()[data["time_label"] > 0], data["time_label"][data["time_label"] > 0]
            )
       ```
change it to 
          ```py
           time_loss = torch.tensor(0).to(self.device) if not self.is_time else self.time_criterion(
                mask_time_output.squeeze()[data["time_label"] > 0], data["time_label"][data["time_label"] > 0]
            )
         ```
