### ISSUE TITLE
Scripts not working

### ISSUE THREAD

**Issue by SMABHISHEK** [HelenGuohx/logbert#5]
cd scripts

#download 2000 hdfs samples for testing and debugging
sh download_hdfs_2k.sh

#download hdfs dataset
sh download_hdfs.sh

#run logbert on HDFS
sh run_logbert_hdfs.sh

Getting issues in #run logbert on HDFS script 

Traceback (most recent call last):
  File "../main_logbert.py", line 4, in <module>
    from logbert.bert_pytorch import Predictor, Trainer
  File "/home/amanjanagowd/testbed/LOGBERT/logbert/logbert/__init__.py", line 1, in <module>
    from .bert_pytorch import Trainer, Predictor
  File "/home/amanjanagowd/testbed/LOGBERT/logbert/logbert/bert_pytorch/__init__.py", line 1, in <module>
    from .model import BERT
  File "/home/amanjanagowd/testbed/LOGBERT/logbert/logbert/bert_pytorch/model/__init__.py", line 1, in <module>
    from .bert import BERT
  File "/home/amanjanagowd/testbed/LOGBERT/logbert/logbert/bert_pytorch/model/bert.py", line 1, in <module>
    import nn as nn
ImportError: No module named nn

**Comment by SMABHISHEK** [comment]
Script names is also inconsistent - Example .logs to .dataset

**Comment by HelenGuohx** [comment]
Hi my code snippet is ```import torch.nn as nn```

**Comment by HelenGuohx** [comment]
Could you be more specific about script names are inconsistent?
.dataset //Stores original datasets after downloading
.output //Stores intermediate files and final results during execution
.logs //Stores execution logs
