### ISSUE TITLE
sh run_logbert_bgl.sh doesn't work

### ISSUE THREAD

**Issue by SMABHISHEK** [HelenGuohx/logbert#6]
Error:

Save options parameters
Traceback (most recent call last):
  File "../main_logbert.py", line 102, in <module>
    main()
  File "../main_logbert.py", line 89, in main
    with open(options["train_vocab"], "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/amanjanagowd/.output/bgl_2k/train'

**Comment by SMABHISHEK** [comment]
Same is the issue with sh run_logbert_hdfs.sh



Save options parameters
Traceback (most recent call last):
  File "../main_logbert.py", line 102, in <module>
    main()
  File "../main_logbert.py", line 89, in main
    with open(options["train_vocab"], "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/amanjanagowd/.output/hdfs/train'

**Comment by HelenGuohx** [comment]
Have you tried to process the data first by running ```sh process_bgl.sh```
